### ISSUE TITLE
Episodes gets detected as video podcast

### ISSUE THREAD

**Issue by HenrikBacher** [drpodcastnu/DR1ommer#3]
With the current parsing the mp4 files for the episodes gets selected, for example this one for the latest episode: https://api.dr.dk/radio/v1/assetlinks/urn:dr:radio:episode:658439fd163dfa22d546bc24/d17f46b37309f973e7342e0f552407a73ea873a784349efff60309479900c311 this url gets redirected to a file stored on akamei which has the content-type video/mp4.

Some podcast players, in my case Pocket casts there for starts it as a video podcast, where as the mp3 links get redirected to file with the correct content-type, audio/mpeg

**Comment by drpodcastnu** [comment]
Tak for dit fix, jeg sørger for at opdatere!
