### ISSUE TITLE
add support for Hvem er

### ISSUE THREAD

**Issue by klgn** [drpodcastnu/DR1ommer#6]
Please add the Hvem er podcast to the list of supported podcasts. https://www.dr.dk/lyd/p3/hvem-er-2522729828000

**Comment by LukasDahl** [comment]
I second this. It is not exclusive to DR Lyd but very heavily timegated on the open RSS feed. It makes for a frustrating experience.

**Comment by drpodcastnu** [comment]
@klgn @LukasDahl Now added :)
